# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SupervisedClassification
                                 A QGIS plugin
 A plugin to classify selected raster file with reference
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-15
        copyright            : (C) 2024 by Mirjan Ali Sha
        email                : mastools.help@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SupervisedClassification class from file SupervisedClassification.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .supervised_classifier import SupervisedClassification
    return SupervisedClassification(iface)
